# Generated by Django 6.1 on 2026-08-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycustomuser',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
