# Generated by Django 6.1 on 2026-08-29 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={'permissions': [('change_todo_status', 'Can change todo status')]},
        ),
    ]
